version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "00:00"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"
    groups:
      babel:
        patterns:
          - '@babel/*'
          - lint-staged
      eslint:
        patterns:
          - eslint*
          - prettier
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "00:00"
    commit-message:
      prefix: "ci"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"
